In [109]:
import pandas as pd

In [110]:
data=pd.read_csv("diabetes.csv")

In [111]:
data.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [112]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [113]:
data.shape

(768, 9)

In [114]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [115]:
data.duplicated().sum()

np.int64(0)

In [116]:
data.Outcome.unique()   # Two categories means binary classification

array([1, 0])

In [166]:
X=data.drop("Outcome",axis=1)
y=data.Outcome

In [118]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=123)

In [119]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()

In [120]:
log_reg.fit(X_train,y_train)

D:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [121]:
y_pred_train=log_reg.predict(X_train)

In [122]:
y_pred_train

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [123]:
count=0
for o,p in zip(y_train,y_pred_train):
    if o==p:
        count+=1
accuracy=f"Accuracy:{(count/len(y_train)) *100}%"
accuracy

'Accuracy:77.36156351791531%'

In [124]:
list(zip(y_train,y_pred_train))

[(0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (1, np.int64(1)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(1)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(1)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(1)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(1)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (1, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (1, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(1)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (1, np.int64(1)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(1)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0)),
 (0, np.int64(0)),
 (0, np.int64(0)),
 (1, np.int64(0))]

In [125]:
y_train.shape

(614,)

In [126]:
y_pred_test=log_reg.predict(X_test)

In [127]:
y_pred_test

array([1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [128]:
count=0
for o,p in zip(y_test,y_pred_test):
    if o==p:
        count+=1
accuracy=f"Accuracy:{(count/len(y_test)) *100}%"
accuracy

'Accuracy:79.22077922077922%'

In [129]:
data.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [130]:
from sklearn.metrics import accuracy_score

In [131]:
accuracy_score(y_train,y_pred_train)

0.7736156351791531

In [132]:
accuracy_score(y_test,y_pred_test)

0.7922077922077922

### Accuracy,Precision and Recall

#### Confusion Matrix

In [133]:
from sklearn.metrics import confusion_matrix,precision_score,recall_score,f1_score

In [134]:
confusion_matrix(y_train,y_pred_train)

array([[361,  43],
       [ 96, 114]])

In [135]:
precision_score(y_train,y_pred_train)

0.7261146496815286

In [136]:
recall_score(y_train,y_pred_train)

0.5428571428571428

In [137]:
f1_score(y_train,y_pred_train)

0.6212534059945504

In [138]:
from sklearn.metrics import classification_report

In [139]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.79      0.89      0.84       404
           1       0.73      0.54      0.62       210

    accuracy                           0.77       614
   macro avg       0.76      0.72      0.73       614
weighted avg       0.77      0.77      0.76       614

In [140]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.79      0.91      0.84        96
           1       0.80      0.60      0.69        58

    accuracy                           0.79       154
   macro avg       0.79      0.75      0.77       154
weighted avg       0.79      0.79      0.79       154

In [141]:
data.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [142]:
class_0=data[data.Outcome==0].sample(268)

In [143]:
class_1=data[data.Outcome==1].sample(268)

In [144]:
data1=pd.concat([class_0,class_1]).sample(536)

In [145]:
data1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
217,6,125,68,30,120,30.0,0.464,32,0
760,2,88,58,26,16,28.4,0.766,22,0
709,2,93,64,32,160,38.0,0.674,23,1
561,0,198,66,32,274,41.3,0.502,28,1
625,4,90,88,47,54,37.7,0.362,29,0
...,...,...,...,...,...,...,...,...,...
619,0,119,0,0,0,32.4,0.141,24,1
414,0,138,60,35,167,34.6,0.534,21,1
603,7,150,78,29,126,35.2,0.692,54,1
739,1,102,74,0,0,39.5,0.293,42,1
747,1,81,74,41,57,46.3,1.096,32,0

In [146]:
data1.Outcome.value_counts()

Outcome
0    268
1    268
Name: count, dtype: int64

In [147]:
X1=data1.drop("Outcome",axis=1)
y1=data1.Outcome

In [148]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X1,y1,test_size=0.20,random_state=1234)

In [149]:
from sklearn.linear_model import LogisticRegression

In [150]:
log_reg=LogisticRegression()

In [151]:
log_reg.fit(X_train,y_train)

D:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [152]:
y_pred_train=log_reg.predict(X_train)

In [153]:
y_pred_test=log_reg.predict(X_test)

In [154]:
from sklearn.metrics import classification_report

In [155]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.74      0.78      0.76       219
           1       0.76      0.72      0.74       209

    accuracy                           0.75       428
   macro avg       0.75      0.75      0.75       428
weighted avg       0.75      0.75      0.75       428

In [156]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.67      0.84      0.75        49
           1       0.83      0.66      0.74        59

    accuracy                           0.74       108
   macro avg       0.75      0.75      0.74       108
weighted avg       0.76      0.74      0.74       108

In [167]:
from imblearn.over_sampling import SMOTE

In [168]:
smote=SMOTE(sampling_strategy="minority",random_state=34)
X,y=smote.fit_resample(X,y)
y.value_counts()

Outcome
1    500
0    500
Name: count, dtype: int64

In [169]:
from sklearn.model_selection import train_test_split

In [175]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=123)

In [176]:
from sklearn.linear_model import LogisticRegression

In [177]:
log_regr=LogisticRegression()

In [178]:
log_regr.fit(X_train,y_train)

D:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [179]:
y_pred_train=log_regr.predict(X_train)

In [180]:
y_pred_test=log_regr.predict(X_test)

In [181]:
from sklearn.metrics import classification_report

In [183]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.76      0.77      0.76       402
           1       0.76      0.75      0.76       398

    accuracy                           0.76       800
   macro avg       0.76      0.76      0.76       800
weighted avg       0.76      0.76      0.76       800

In [184]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.73      0.64      0.68        98
           1       0.69      0.77      0.73       102

    accuracy                           0.71       200
   macro avg       0.71      0.71      0.71       200
weighted avg       0.71      0.71      0.71       200

In [200]:
df=pd.read_csv("diabetes.csv")

In [201]:
df.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
Glucose,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
BloodPressure,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
SkinThickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
Insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
BMI,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
DiabetesPedigreeFunction,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
Age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
Outcome,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

In [202]:
X=df.drop(["BloodPressure","SkinThickness","Outcome"],axis=1)
y=df.Outcome

In [203]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy='minority', random_state=42)
X,y = smote.fit_resample(X,y)

In [206]:
from sklearn.model_selection import train_test_split

In [207]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=123)

In [208]:
#Lets first we can scale this data
from sklearn.preprocessing import MinMaxScaler

In [209]:
scaler=MinMaxScaler()

In [210]:
scaler.fit(X_train)

MinMaxScaler()

In [215]:
X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)

In [216]:
from sklearn.linear_model import LogisticRegression

In [217]:
logi_reg=LogisticRegression()

In [218]:
logi_reg.fit(X_scaled_train,y_train)

LogisticRegression()

In [222]:
y_pred_train=logi_reg.predict(X_scaled_train)

In [223]:
y_pred_test=logi_reg.predict(X_scaled_test)

In [226]:
from sklearn.metrics import classification_report


print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.72      0.77      0.74       354
           1       0.74      0.69      0.71       346

    accuracy                           0.73       700
   macro avg       0.73      0.73      0.73       700
weighted avg       0.73      0.73      0.73       700

In [227]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.75      0.74      0.74       146
           1       0.76      0.77      0.76       154

    accuracy                           0.75       300
   macro avg       0.75      0.75      0.75       300
weighted avg       0.75      0.75      0.75       300