In [1]:
import pandas as pd

In [2]:
house=pd.read_excel("Bengaluru_House_Data.xlsx")

In [3]:
house.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,2026-12-19 00:00:00,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [4]:
len(house.area_type.unique())

4

In [5]:
len(house.availability.unique())

81

In [6]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [7]:
len(house.location.unique())

1295

In [8]:
len(house.society.unique())

2689

In [9]:
house.drop(["availability","location","society"],axis=1,inplace=True)

In [10]:
house.head()

              area_type       size total_sqft  bath  balcony   price
0  Super built-up  Area      2 BHK       1056   2.0      1.0   39.07
1            Plot  Area  4 Bedroom       2600   5.0      3.0  120.00
2        Built-up  Area      3 BHK       1440   2.0      3.0   62.00
3  Super built-up  Area      3 BHK       1521   3.0      1.0   95.00
4  Super built-up  Area      2 BHK       1200   2.0      1.0   51.00

In [11]:
house.isna().sum()

area_type       0
size           16
total_sqft      0
bath           73
balcony       609
price           0
dtype: int64

In [12]:
house.fillna({"size":house['size'].mode()[0],
             "bath":house.bath.median(),
             "balcony":0},inplace=True)

In [13]:
house["BHK"]=house["size"].apply(lambda x:x.split(" ")[0]).astype(int)

In [14]:
house.head()

              area_type       size total_sqft  bath  balcony   price  BHK
0  Super built-up  Area      2 BHK       1056   2.0      1.0   39.07    2
1            Plot  Area  4 Bedroom       2600   5.0      3.0  120.00    4
2        Built-up  Area      3 BHK       1440   2.0      3.0   62.00    3
3  Super built-up  Area      3 BHK       1521   3.0      1.0   95.00    3
4  Super built-up  Area      2 BHK       1200   2.0      1.0   51.00    2

In [15]:
house.drop("size",axis=1,inplace=True)

In [16]:
house.total_sqft.unique()

array([1056, 2600, 1440, ..., '1133 - 1384', 774, 4689],
      shape=(2117,), dtype=object)

In [17]:
house=house[house.total_sqft.astype(str).str.isnumeric()]

In [18]:
house.total_sqft=house.total_sqft.astype(float)

In [19]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [20]:
ohe=OneHotEncoder()

In [21]:
area_type_encoded=ohe.fit_transform(house[["area_type"]]).toarray()

In [22]:
area_type_encoded=pd.DataFrame(area_type_encoded,columns=ohe.get_feature_names_out())

In [23]:
house=pd.concat([house,area_type_encoded],axis=1)

In [24]:
house.drop("area_type",axis=1,inplace=True)

In [25]:
house.head()

,total_sqft,bath,balcony,price,BHK,area_type_Built-up Area,area_type_Carpet Area,area_type_Plot Area,area_type_Super built-up Area
0,1056.0,2.0,1.0,39.07,2.0,0.0,0.0,0.0,1.0
1,2600.0,5.0,3.0,120.00,4.0,0.0,0.0,1.0,0.0
2,1440.0,2.0,3.0,62.00,3.0,1.0,0.0,0.0,0.0
3,1521.0,3.0,1.0,95.00,3.0,0.0,0.0,0.0,1.0
4,1200.0,2.0,1.0,51.00,2.0,0.0,0.0,0.0,1.0

### Split Data

In [35]:
house.dropna(inplace=True)

In [37]:
X=house.drop("price",axis=1)
y=house.price

In [38]:
X.shape

(12659, 8)

In [39]:
y.shape

(12659,)

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=93)

### Feature Scaling

In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
sc=StandardScaler()

In [47]:
sc.fit(X_train)

StandardScaler()

In [48]:
X_train=sc.transform(X_train)
X_test=sc.transform(X_test)

In [51]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error

In [ ]:
#training